version: "3"

services:
  # ------> reactjs ------>
  charlyjs:
    container_name: charlyjs
    build: ./reactjs
    image: charlyjs
    ports:
      - 3000:3000
    network_mode: host
    volumes:
      - ../:/app